name: Update ih8sn config

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Update ih8sn.conf
      run: |
        python config_update.py
    - name: Commit and push changes
      id: commit
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"
        git add .
        git commit -m "$(cat system/etc/ih8sn.conf | sed -n '/PRODUCT_NAME/!p' | sed 's/BUILD_FINGERPRINT=//g')" && \
          echo "::set-output name=commit::true" && git push || \
          echo "::set-output name=commit::false" && exit 0
    - name: Trigger build workflow
      if: steps.commit.outputs.commit == 'true'
      run: |
        curl -XPOST -u "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        "https://api.github.com/repos/${{ github.repository }}/dispatches" \
        -d '{"event_type": "build"}'
